# Generated by Django 3.2.8 on 2021-10-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kookaburra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kookaburrasection',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
