# Generated by Django 3.2.8 on 2021-10-31 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kookaburra', '0002_alter_kookaburrasection_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='kookaburrasection',
            name='slug',
            field=models.SlugField(default='example'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kookaburrapost',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
