# Generated by Django 3.2.8 on 2021-11-01 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kookaburra', '0004_auto_20211031_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kookaburrapost',
            name='section',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='kookaburra.kookaburrasection'),
        ),
    ]
