# Generated by Django 3.2.8 on 2021-11-28 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('kookaburra', '0005_alter_kookaburrapost_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='kookaburrapost',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='kookaburrasection',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinates_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kookaburrapost',
            name='followers',
            field=models.ManyToManyField(related_name='posts_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
